server:
  # 服务端口
  port: 8080

spring:
  application:
    # 服务应用名称
    name: eureka

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      # 服务注册的URL
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


